[package]
name = "cryptopals"
version = "0.1.0"
authors = ["divyank"]
edition = "2018"

[dependencies]
base64 = "0.10.1"
hex = "0.3.2"
num-bigint = {version= "0.2.3", features = ["rand"]}
num-traits = "0.2.8"
openssl = "0.10.23"
rand = "0.6.5"
rocket = "0.4.2"
rust-crypto = "0.2.36"
url = "2.0.0"
